version: '3.9'
services:
  db:
    container_name: staging_area_prototype_db
    build: .
    ports:
      - "1433:1433"
    volumes:
        - ./scripts:/scripts
        - sqlvolume:/var/opt/mssql

  redis:
    container_name: staging_area_prototype_redis
    image: redis:7.0.11-alpine3.18
    ports:
      - "6379:6379"
volumes:
  sqlvolume: