version: '3.9'
services:
  db:
    container_name: best_fit_db
    build: .
    ports:
      - "1433:1433"
    volumes:
        - ./scripts:/usr/src/app/scripts
        - sqlvolume:/var/opt/mssql

  redis:
    container_name: best_fit_cache
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  sqlvolume: